### ISSUE TITLE
MacOS development migrations fail

### ISSUE THREAD

**Issue by christopherowen** [QoboLtd/project-template-cakephp#1028]
This is a (multiple allowed):

* [x] bug

* Version of project-template-cakephp: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
during
```
./bin/build app:install DB_NAME="app",PROJECT_NAME="My Project",PROJECT_VERSION="v1.0.0"
```

received
```
 [Qobo\Cakephp\Migration] Running ./bin/cake migrations migrate -p 'Search' --connection='test'
Exception: Module `Users` does not exist. in [/Users/swank/projects/david/project-template-cakephp/vendor/qobo/cakephp-utils/src/Module/ModuleRegistry.php, line 122]
2020-08-02 22:55:05 Error: [Qobo\Utils\Module\Exception\MissingModuleException] Module `Users` does not exist. in /Users/swank/projects/david/project-template-cakephp/vendor/qobo/cakephp-utils/src/Module/ModuleRegistry.php on line 122
Stack Trace:
#0 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(94): Qobo\Utils\Module\ModuleRegistry->_throwMissingClassError('Users', NULL)
#1 /Users/swank/projects/david/project-template-cakephp/vendor/qobo/cakephp-utils/src/Module/ModuleRegistry.php(77): Cake\Core\ObjectRegistry->load('Users', Array)
#2 /Users/swank/projects/david/project-template-cakephp/src/Model/Table/UsersTable.php(42): Qobo\Utils\Module\ModuleRegistry::getModule('Users')
#3 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(299): App\Model\Table\UsersTable->initialize(Array)
#4 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(293): Cake\ORM\Table->__construct(Array)
#5 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(249): Cake\ORM\Locator\TableLocator->_create(Array)
#6 /Users/swank/projects/david/project-template-cakephp/vendor/cakedc/users/src/Controller/Traits/CustomUsersTableTrait.php(36): Cake\ORM\Locator\TableLocator->get('Users')
#7 /Users/swank/projects/david/project-template-cakephp/vendor/qobo/cakephp-search/src/Model/Table/SavedSearchesTable.php(49): Search\Model\Table\SavedSearchesTable->getUsersTable()
#8 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/Table.php(299): Search\Model\Table\SavedSearchesTable->initialize(Array)
#9 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(293): Cake\ORM\Table->__construct(Array)
#10 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(249): Cake\ORM\Locator\TableLocator->_create(Array)
#11 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/ORM/TableRegistry.php(148): Cake\ORM\Locator\TableLocator->get('Search.SavedSea...', Array)
#12 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/TableFinderTrait.php(168): Cake\ORM\TableRegistry::get('Search.SavedSea...')
#13 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/TableFinderTrait.php(111): Migrations\Command\Dump->fetchTableName('Search.SavedSea...', 'Search')
#14 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/TableFinderTrait.php(58): Migrations\Command\Dump->getTableNames('Search')
#15 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/Command/Dump.php(92): Migrations\Command\Dump->getTablesToBake(Object(Cake\Database\Schema\Collection), Array)
#16 /Users/swank/projects/david/project-template-cakephp/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Dump->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/swank/projects/david/project-template-cakephp/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/swank/projects/david/project-template-cakephp/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Dump), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/swank/projects/david/project-template-cakephp/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/Shell.php(531): Migrations\Shell\MigrationsShell->main('migrations', 'dump')
#22 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(169): Cake\Console\Shell->runCommand(Array, true, Array)
#23 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(229): Migrations\Shell\MigrationsShell->runCommand(Array, true, Array)
#24 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(181): Cake\Console\ShellDispatcher->_dispatch(Array)
#25 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/Shell.php(418): Cake\Console\ShellDispatcher->dispatch(Array)
#26 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(128): Cake\Console\Shell->dispatchShell('migrations dump...')
#27 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/Shell.php(531): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#28 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(169): Cake\Console\Shell->runCommand(Array, true, Array)
#29 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/CommandRunner.php(384): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#30 /Users/swank/projects/david/project-template-cakephp/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#31 /Users/swank/projects/david/project-template-cakephp/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#32 {main}


 [Qobo\Cakephp\Migration]  Last command failed to run 
 [Qobo\Cakephp\Migration]  Exit code 1 
 [error]  Failed to do app:install 
```

### What happened
Not sure

### What you expected to happen
completed application install

**Comment by christopherowen** [comment]
tag v50.3.0 has a very similar error, but with the "Things" module.

**Comment by christopherowen** [comment]
tag v50.2.3 no longer has these errors.

Perhaps this is related to the accompanying downgrade of the cakephp-csv-migrations module to v36.2.1.
